version: '2.1'
services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
    expose:
      - "8000"
    links:
      - mysql
      #- redis
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DJANGO_DOCKER: 1
  #
  #redis:
  #  image: redis:latest
  #  volumes:
  #    - /var/lib/redis
  #  ports:
  #    - "6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./src/config/nginx:/etc/nginx/conf.d
    links:
      - web
    depends_on:
      - web

  mysql:
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    ports:
      - "33306:3306"
    healthcheck:
      test: mysqladmin -uroot -phubs ping
      interval: 2s
      timeout: 5s
      retries: 30
    environment:
      MYSQL_ROOT_PASSWORD: hubs
      MYSQL_DATABASE: hubs
